### PR TITLE
Update to accept parser so that versions can be accepted without a v …

### LINKED ISSUE #543: If you don't have the letter "v" as a prefix to your version - it breaks Dingo
Dingo will not match based on the presumed pattern for the version.

For example, if I set my api versions as 1.0, 2.0.etc. (instaed of v1.0, v2.0) then the pattern matching within the accept class fails.

### PR DESCRIPTION
**Pull request by kirkbushell**
Resolves #543.

### CODE REVIEW

**Comment by bweston92** [comment]
I believe that having the `v` prefix actually lets people know it is a version number.

**Comment by kirkbushell** [comment]
That may be so, but it shouldn't be a requirement. The way API versions are done with Dingo I actually find quite odd (rather than being a separate header).

It caught me up, and caused exceptions/issues that were hard to track down and debug. It's also not documented.

**Comment by lightvision** [comment]
I also beleave this even somerimes I would ti have the liberty to name versions withot v.
Accepting versions without v wouldn't involve a change to api docs too?

**Comment by kirkbushell** [comment]
I don't see how - it would simply mean that the package doesn't make any assumptions about how you name your versions. What if you want to use codenames instead? Like "Icecream Sandwich" :)

**Comment by lightvision** [comment]
@jasonlewis What do you think about this?

@kirkbushell I got your point. I was annoyed too about forcing me to put a v before the actual version, but I had to move over for the moment, this is something I can leave with.

**Comment by jasonlewis** [comment]
I'm fine with this. I guess it's a silly limitation. As for the header, I personally don't like making a new request header. Content negotiation is best done with the `Accept` header. I really need to document vendor prefixes a bit better though as *technically* they need to be registered with the IANA. I want to tweak content negotiation a bit.

**Pull request merged**
