### PR TITLE
Do not throttle internal requests

### PR DESCRIPTION
**Pull request by lucasmichot**
This PR targets #751 .
@aleemb @jasonlewis @vinkla thoughts and suggestions are welcome

### CODE REVIEW

**Comment by vinkla** [comment]
LGTM.

**Comment by aleemb** [comment]
Looking good, that was quick. Thanks much!

Aleem

**Comment by jasonlewis** [comment]
I wouldn't hand off to the next request until we confirm the request is indeed internal. Just run the `$next($request)` twice, it's no biggie.

Otherwise the rate limiting is pretty much void as you're essentially firing off the request by handing it off to the next middleware (until the route itself is fired).

**Comment by lucasmichot** [comment]
@jasonlewis , I am not sure what you mean ?
"hand off" ?

**Comment by lucasmichot** [comment]
OK, I see. NVM
See: 211d4179a6e3908795380b2803051f5dd011e314

**Pull request merged**
