### PR TITLE
support base path config/api.php

### PR DESCRIPTION
**Pull request by vanntian**
like laravel 5 config file

### CODE REVIEW

**Comment by jasonlewis** [comment]
Doesn't `mergeConfigFrom` merge the two together so that the user defined configuration overwrites the config in the package (which this method supplies the path for)?

**Comment by vanntian** [comment]
@jasonlewis yes

**Comment by bweston92** [comment]
@jasonlewis yes that is correct, this merge request stops the app specific and default merging.

**Comment by jasonlewis** [comment]
So what's the benefit here exactly...

**Comment by bweston92** [comment]
I actually think that it would merge an application specific configuration with it-self, as the first argument is supposed to be the path to the package specific configuration.

**Comment by jasonlewis** [comment]
Yeah I don't think this does what's intended. The idea of `mergeConfigFrom` is to merge the default configuration in the package with the application specific configuration.

**Comment by natsu90** [comment]
So anyway we can have this? I just realised my Lumen doesn't pick up config from base path. I've to add `$app->configure('api')` in `bootstrap/app.php` myself.

**Comment by jasonlewis** [comment]
Okay I think I see what's happening here for Lumen installs. Let me work on something.

**Comment by jasonlewis** [comment]
I've made a change that automatically configures it with `$app->configure` so you don't need to worry about it. It merges the default package configuration as well.

**Comment by natsu90** [comment]
Thanks.

**Pull request closed without merging**
