### PR TITLE
Take into consideration all files types and yaml

### PR DESCRIPTION
**Pull request by lucasmichot**
Also .yml files need to be taken into consideration

### CODE REVIEW

**Comment by vinkla** [comment]
I'd argue this file should be removed all together. Since we just recently integrated both PHP CS Fixer and StyleCI. I no longer see the use of this file. It doesn't affect this package. Only for some users who have this integrated within there editors.

**Comment by GrahamCampbell** [comment]
This file is probably fine to stay.

**Comment by GrahamCampbell** [comment]
StyleCI itself has this file, even though StyleCI is enabled on StyleCI. :P

**Comment by lucasmichot** [comment]
this are different things @vinkla , PHP-CS-Fixer primary goals is not to fix json, yaml and so on

**Comment by lucasmichot** [comment]
Failing tests ? 5.1 stable ??

**Comment by vinkla** [comment]
It exists for another purpose then the CS Fixer and StyleCI but it doesn't do anything for the library. It is custom setup for the developers building this package. That is my opinion.

**Comment by lucasmichot** [comment]
Sure @vinkla 
I presume @jasonlewis will be glad to get only 4 spaces in composer.json files and not tabs in commits, or at least to avoid it

**Pull request merged**
