### PR TITLE
Fractal's support for L5 starts in 0.12 versions.

### PR DESCRIPTION
**Pull request by bweston92**

### CODE REVIEW

**Comment by tymondesigns** [comment]
version should be `0.12.*@dev` for now right ?

**Comment by GrahamCampbell** [comment]
> version should be 0.12.*@dev for now right ?

No.

**Comment by duxet** [comment]
0.12 have been released 8 days ago :)

**Comment by jasonlewis** [comment]
Not merging anything L5 related as yet as the upgrade is going to be a little more complicated than I initially thought it would be. Cheers.

**Pull request closed without merging**
