### PR TITLE
CS Fixes

### PR DESCRIPTION
**Pull request by GrahamCampbell**
This makes sure your actual coding style is enforced. You seem to be following many more rules than just PSR-2. Let me know if I've enabled a fixer you didn't want by mistake.

### CODE REVIEW

**Comment by jasonlewis** [comment]
Where does the comma after the final array come into play? Looks gross IMO. :grin:

**Comment by jasonlewis** [comment]
I think the only thing I do is `if (! $whatever)`, where there's a space after the exclamation mark. I'm not sure PSR-2 makes any recommendations there do they?

Where do I not follow PSR-2?

**Comment by GrahamCampbell** [comment]
> Where does the comma after the final array member come into play? Looks gross IMO.

Sure I can disable it. You just have some places where you have trailing commas, and there's no fixer to remove them. The main advantage to having trailing commas is regarding only changing one line when adding to an array thus reducing merge conflicts and having clearer diffs.

> I think the only thing I do is if (! $whatever), where there's a space after the exclamation mark. I'm not sure PSR-2 makes any recommendations there do they?

Yeh, that's allowed in PSR-2. I recently enabled that fixer on laravel/framework.

> Where do I not follow PSR-2?

You do follow PSR-2. What I meant is you also have additional rules that you're using on top of PSR-2, but you weren't actually enforcing them before.

**Comment by jasonlewis** [comment]
I'll just have to get over the ugliness of it. Won't take me long. :stuck_out_tongue:

**Comment by jasonlewis** [comment]
Cheers @GrahamCampbell! :+1:

**Comment by GrahamCampbell** [comment]
No problem. :)

**Pull request merged**
