### PR TITLE
Allow https route declaration with 'https' array key and value

### PR DESCRIPTION
**Pull request by gazben**
Allow https route declaration with 'https' array key and value.
```
$router->group(['https' => true], function (Router $router) {
});
```

### CODE REVIEW

**Comment by gazben** [comment]
@specialtactics Can you merge this? Or do you think it will beak stuff?

**Comment by specialtactics** [comment]
Can't imagine any issues, but I guess we will have to see! I ran tests on a couple of projects I have and no issues, so merging.

**Comment by Derjuju** [comment]
Is this not a breaking change that prevent upgrading to Laravel/Lumen 6.x ?
#1689
Illuminate\Routing\Route return true/false on httpOnly if '**http**' is in action array
Dingo\Api\Routing\Route return true/false on httpOnly if '**https**' is in action array

Dingo\Api\Routing\Route extends Illuminate\Routing\Route

httpOnly, httpsOnly and secure methods shouldn't be overrided. They should keep the parent class logic.

Returning true with httpOnly when 'https' is set, is a non-sense... I think.

**Comment by gazben** [comment]
@Derjuju  Oh my god, I messed this up. You are right. It should go to the httpsOnly/secure() function. I'll create the pull request

**Pull request merged**
