### PR TITLE
API_STRICT only for specific URLs

### PR DESCRIPTION
**Pull request by Barmunksu**
API_STRICT only for specific URLs with $request->is pattern

### CODE REVIEW

**Comment by thilanga** [comment]
@Barmunksu Can you explain me what is this really useful or your use case?

**Comment by thilanga** [comment]
No Response from the author

**Comment by lloricode** [comment]
@thilanga 

hi this is helpful when you need to make some listener for external sites, like verifying user from url on their email, redirecting this will use `GET` with no headers, so this api listener will cannot interacting with given url if it has a `strict` rule to all routes

**Comment by lloricode** [comment]
please merge this or, enhance if needed

**Comment by specialtactics** [comment]
Can't you just not have the struct rule on all routes? @lloricode

**Comment by lloricode** [comment]
yes but it is helpful when uses `strict`, the only downside is cannot control which route can be apply for this

**Comment by specialtactics** [comment]
I understand @lloricode unfortunately this cannot be a priority right now to look at.

**Pull request closed without merging**
