### PR TITLE
Fix Paginator reference to LengthAwarePaginator

### PR DESCRIPTION
**Pull request by tymondesigns**
Cannot get the paginator response to work using the response factory because fractal requires an instance of `LengthAwarePaginator` in the `IlluminatePaginatorAdapter` [here](https://github.com/thephpleague/fractal/blob/master/src/Pagination/IlluminatePaginatorAdapter.php#L38).

All works great after this change.

### CODE REVIEW

**Comment by jasonlewis** [comment]
Is it perhaps worth type-hinting the `AbstractPaginator` instead of `LengthAwarePaginator` in case people aren't using Fractal but would like to use the regular `Paginator` instance?

**Comment by tymondesigns** [comment]
Yep, that would be better I think.. Will tweak and rebase when I'm home

**Comment by jasonlewis** [comment]
All good mate. Cheers.

**Comment by tymondesigns** [comment]
Messed up my history 😪 Tried to target master as everything has been merged over..

#454 now targets master and has the changes as suggested

**Pull request closed without merging**
