### PR TITLE
Add GIT attributes file

### PR DESCRIPTION
**Pull request by vinkla**
In production we don't want to download the test files.

### CODE REVIEW

**Comment by lucasmichot** [comment]
Probably lots of other files at the root to add to `.gitignore`

**Comment by vinkla** [comment]
Yeah, we could add everything except the `composer.json`, `config` and `src` if we want to save more space. @jasonlewis What do you think?

**Comment by lucasmichot** [comment]
I would add .editorconfig, .travis.yml and phpunit.xml

**Comment by vinkla** [comment]
I would go with either just the test folder or something like this;

```
/tests export-ignore
/.gitattributes export-ignore
/.gitignore export-ignore
/.travis.yml export-ignore
/phpunit.xml.dist export-ignore
/CHANGELOG.md export-ignore
/CONTRIBUTING.md export-ignore
/README.md export-ignore
```

**Comment by jasonlewis** [comment]
Yeah all the cruff can probably be ignored.

**Comment by vinkla** [comment]
Done.

**Pull request merged**
