### PR TITLE
Fix FormRequests missing class error

### PR DESCRIPTION
**Pull request by gazben**
Lumen does not contain the Illuminate\Foundation\Http\FormRequest class.

I merged the original file and the Laravel FormRequest class into the Dingo FormRequest class.

I added the ValidatesWhenResolvedTrait resolving to the LumenServiceProvider too.

### CODE REVIEW

**Comment by sakalauskas** [comment]
@thilanga @gazben FYI this PR breaks dingo on Laravel. 

In LaravelServiceProvider we need to add ```$this->app->resolving(FormRequest...``` too, but problem is that we cannot set the redirector property as in Laravel class is named "Illuminate\Routing\Redirector" and in Lumen it is named "Laravel\Lumen\Http\Redirector" and unfortunately there is no Redirector contract. Thus, I am not sure at the moment how to resolve this nicely.

**Comment by gazben** [comment]
@sakalauskas In my experience it "only" breaks in the latest laravel release. 
I will look into this today/tomorrow.

**Comment by TeroBlaZe** [comment]
@gazben Can't use an application after this PR. Validation fails on POST request with json. Rolled back to previous commit.

**Comment by TeroBlaZe** [comment]
@gazben Laravel

**Comment by gazben** [comment]
@TeroBlaZe @sakalauskas I can only present an ugly solution:
https://github.com/Brixify/api/commit/e6a2d2cd5fa3e42954e6358d364375dbd38adea2

Without a Redirector contract I don't think I can do more. What do you think? (works on my machine)

**Comment by gazben** [comment]
@TeroBlaZe @sakalauskas I created another pull request for the issue.

**Comment by sakalauskas** [comment]
@gazben This looks fine to me.

**Pull request merged**
