### PR TITLE
reopen https://github.com/dingo/api/pull/1680

### PR DESCRIPTION
**Pull request by lloricode**
https://github.com/dingo/api/pull/1680

### CODE REVIEW

**Comment by specialtactics** [comment]
Let me check out the travis failures

**Comment by lloricode** [comment]
thanks :)

**Comment by specialtactics** [comment]
Hey @lloricode would you mind pulling/syncing the latest dingo master, and see if that fixes the issue.

**Comment by lloricode** [comment]
@specialtactics yes, wait a few minutes :)

**Comment by lloricode** [comment]
done :+1:

**Comment by specialtactics** [comment]
Awesome, thanks !

**Pull request merged**
