### PR TITLE
Use Container Contract. Fixes #805.

### LINKED ISSUE #805: Error in Dingo\Api\Http\Middleware\Request in lumen 5.2
The problem is that in Lumen 5.2 (for some reason) ``Laravel\Lumen\Application`` no longer implements ``\Illuminate\Contracts\Foundation\Application``.

This causes ``Dingo\Api\Http\Middleware\Request`` constructor to fail.

I fixed it by replacing ``\Illuminate\Contracts\Foundation\Application`` with ``\Illuminate\Contracts\Container\Container``, which will work both on Laravel and Lumen.

I am not happy with this fix, or I would PR it...

### PR DESCRIPTION
**Pull request by irazasyed**

### CODE REVIEW

**Comment by irazasyed** [comment]
StyleCI seems to be analysing the wrong file? The file it shows is not what was changed. Weird.

**Comment by lucasmichot** [comment]
Ping @GrahamCampbell

**Comment by adamgoose** [comment]
This was cleaned up a bit more in #811.

**Comment by arthurkirkosa** [comment]
Is this package maintained anymore? @jasonlewis

**Comment by tymondesigns** [comment]
Jason has been away for the holidays, that's all

https://twitter.com/jasonclewis/status/690000332022226946?s=09

**Comment by lucasmichot** [comment]
Ah ah ah ! I really thought the question was about `\Illuminate\Contracts` !!

**Pull request closed without merging**
