### PR TITLE
fixed accept header regex

### PR DESCRIPTION
**Pull request by gxela**

### CODE REVIEW

**Comment by jasonlewis** [comment]
How are you doing your versions?

**Comment by gxela** [comment]
I would like to be able to have this flexibility in my api versioning

**Comment by gxela** [comment]
It doesn't hurt to add this, It allows me to add more detailed versioning to my architecture and so I would like to not have to modify this file everytime I composer update

**Comment by bweston92** [comment]
Create your own service provider for dingo and construct your own router that extends dingo's router.



—

**Comment by jasonlewis** [comment]
For the L5/Lumen versions you can overload the Accept parser now and do it how you want.

**Pull request closed without merging**
