### PR TITLE
Use stricter tests assertions

### PR DESCRIPTION
**Pull request by lucasmichot**
Use stricter tests assertions

### CODE REVIEW

**Comment by lucasmichot** [comment]
I do think there should be a config key for Styleci, that enable the style to be checked only on added or modified files within a PR
Ping @GrahamCampbell

**Comment by GrahamCampbell** [comment]
Nah, StyleCI isn't built for that. TBH, the PR status is a waste of time IMO, but people seem to want it.

**Comment by GrahamCampbell** [comment]
The real use case is turn it on, and forget about it. I have no interest in partial fixing.

**Comment by hskrasek** [comment]
Looks good to me @lucasmichot

**Pull request merged**
