### PR TITLE
fix blueprint version

### PR DESCRIPTION
**Pull request by Remo**
had to make this branch in order to get it working with larvel 5.2

### CODE REVIEW

**Comment by crynobone** [comment]
You actually need to change your composer.json

```
"prefer-stable": true,
"minimum-stability": "dev"
```

Or 

```
"require": {
  "dingo/blueprint": "0.2@dev"
},
```

But I personally would prefer the first option, since `dingo/api` isn't even have a stable `1.0` release yet.

**Comment by Remo** [comment]
Either way, we should at least make a note somewhere to tell people how to use this with Laravel 5.2..

**Comment by ghprod** [comment]
already use this

```
"prefer-stable": true,
"minimum-stability": "dev"
```

but still give me error

```
Problem 1
    - dingo/api 1.0.x-dev requires dingo/blueprint 0.2.* -> satisfiable by dingo/blueprint[0.2.x-dev] but these conflict with your requirements or minimum-stability.
    - Conclusion: don't install dingo/api v1.0.0-beta3
    - Installation request for phpdocumentor/reflection-docblock (locked at 3.1.0) -> satisfiable by phpdocumentor/reflection-docblock[3.1.0].
    - Conclusion: remove laravel/framework v5.2.39
    - Conclusion: don't install laravel/framework v5.2.39
    - dingo/api v1.0.0-beta1 requires illuminate/support 5.1.* -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.6, v5.1.8].
    - dingo/api v1.0.0-beta2 requires illuminate/support 5.1.* -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.6, v5.1.8].
    - don't install illuminate/support v5.1.1|don't install laravel/framework v5.2.39
    - don't install illuminate/support v5.1.13|don't install laravel/framework v5.2.39
    - don't install illuminate/support v5.1.16|don't install laravel/framework v5.2.39
    - don't install illuminate/support v5.1.2|don't install laravel/framework v5.2.39
    - don't install illuminate/support v5.1.20|don't install laravel/framework v5.2.39
    - don't install illuminate/support v5.1.22|don't install laravel/framework v5.2.39
    - don't install illuminate/support v5.1.25|don't install laravel/framework v5.2.39
    - don't install illuminate/support v5.1.28|don't install laravel/framework v5.2.39
    - don't install illuminate/support v5.1.30|don't install laravel/framework v5.2.39
    - don't install illuminate/support v5.1.31|don't install laravel/framework v5.2.39
    - don't install illuminate/support v5.1.6|don't install laravel/framework v5.2.39
    - don't install illuminate/support v5.1.8|don't install laravel/framework v5.2.39
    - Installation request for laravel/framework (locked at v5.2.39, required as 5.2.*) -> satisfiable by laravel/framework[v5.2.39].
    - Installation request for dingo/api 1.0.x@dev -> satisfiable by dingo/api[1.0.x-dev, v1.0.0-beta1, v1.0.0-beta2, v1.0.0-beta3].
```

**Comment by crynobone** [comment]
> but these conflict with your requirements or minimum-stability.

Minimum stability is still wrong or mixed of dependencies can't be resolved.

**Pull request closed without merging**
