### PR TITLE
updated dingo/blueprint to satisfy requirements of Laravel 6

### PR DESCRIPTION
**Pull request by Alano13**

### CODE REVIEW

**Comment by denisdulici** [comment]
@specialtactics this is also required

**Comment by lloricode** [comment]
please reopen this

**Comment by specialtactics** [comment]
Hey @lloricode I'm actually not able to re-open because the repository which this came from no longer seems to exist (check the PR details - says unknown repo).

Are there any issues with this? If so, can you explain, and I will fix them.

**Comment by lloricode** [comment]
@specialtactics, done sorry i did not notice the repo is not ecist

**Pull request closed without merging**
