### PR TITLE
Test on PHP 7.0

### PR DESCRIPTION
**Pull request by vinkla**
Still allowing failures though.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1: on this given that mockery doesn't work on php 7 properly yet.

**Comment by vinkla** [comment]
@GrahamCampbell Does it matter? Since we still allow it to fail.

**Comment by GrahamCampbell** [comment]
There's no point in adding something that fatal errors out of our control. Not doing any good at all.

**Comment by vinkla** [comment]
Closing this due to lack of interest.

**Pull request closed without merging**
